version = 0.1
[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "chargeflow"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jft4a7jes4d2"
s3_prefix = "chargeflow"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
