service: rizajumola

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  versionFunctions: false
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
    DATABASE_NAME: ${env:DATABASE_NAME}
    GMAIL_USERNAME: ${env:GMAIL_USERNAME}
    GMAIL_PASSWORD: ${env:GMAIL_PASSWORD}
    MAIL_SENDER: ${env:MAIL_SENDER}
    QUEUE_URL:
      Ref: TaskQueue
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "sqs:SendMessage"
      Resource:
        - Fn::GetAtt: [TaskQueue, Arn]
  region: ${env:AWS_REGION}

resources:
  Resources:
    TaskDLQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: rizajumola-dlq
    TaskQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: rizajumola-queue
        ReceiveMessageWaitTimeSeconds: 20
        VisibilityTimeout: 300
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - TaskDLQueue
              - Arn
          maxReceiveCount: 1

plugins:
  - serverless-offline

functions:
  getProductCatalog:
    handler: src/handlers/catalog.getProducts
  checkout:
    handler: src/handlers/checkout.createOrder
  email:
    handler: src/handlers/email.emailOrder
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - TaskQueue
              - Arn
          batchSize: 10
